defaults: &defaults
  adapter: mysql2
  username: convocator-robot
  password: hccnnrMPnBd8568H
  host: 10.10.1.81

development:
  <<: *defaults
  database: convocator-robot

production:
  <<: *defaults
  database: convocator-robot

